spring.application.name=banking-transfers

# --- Configuración de Base de Datos H2 ---
spring.datasource.url=jdbc:h2:mem:bankingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- Configuración de JPA / Hibernate ---
# Crea las tablas automáticamente basándose en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- LA PIEZA QUE FALTA ---
# Esto obliga a Spring a esperar a que las tablas se creen ANTES de ejecutar el data.sql
spring.jpa.defer-datasource-initialization=true

# --- Consola H2 ---
# Podrás entrar en http://localhost:8080/h2-console para ver tus tablas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Importante para que la consola no bloquee el acceso en navegadores modernos
spring.h2.console.settings.web-allow-others=true

# --- Camel ---
camel.springboot.main-run-controller=true